name    'leonardothibes-vim'
version '1.0.1'
author 'leonardothibes'
license 'MIT'
summary 'Manage Vim via Puppet'
description 'Manage Vim via Puppet'
source 'git://github.com/leonardothibes/puppet-vim.git'
project_page 'http://github.com/leonardothibes/puppet-vim'
