name    'leonardothibes-vim'
version '1.0.0'
source 'UNKNOWN'
author 'leonardothibes'
license 'MIT'
summary 'Manage Vim via Puppet'
source 'git://github.com/leonardothibes/puppet-jekyll.git'
project_page 'http://github.com/leonardothibes/puppet-jekyll'
